name: Scheduled YouTube Script Run

on:
  schedule:
    # This will run the workflow every day at midnight
    - cron:  '50 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust as necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Execute YouTube stats script
      run: |
        python yt_statistics_airtable.py
      env:
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
        AIRTABLE_ACCESS_TOKEN: ${{ secrets.AIRTABLE_ACCESS_TOKEN }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
