name: YouTube Statistics Job

on:
  schedule:
    # This will run the workflow every day at 1 a.m.
    - cron:  '0 1 * * *'

jobs:
  statistics:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare Node.js 16 Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Checkout Code
      uses: actions/checkout@v2
   
    - name: Prepare Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3'  # Adjust as necessary

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run YouTube Statistics Script
      run: python scripts/yt_statistics_airtable.py
      env:
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
        AIRTABLE_ACCESS_TOKEN: ${{ secrets.AIRTABLE_ACCESS_TOKEN }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
